//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEPROM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EEPROM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Anterior Blue Mode.
        /// </summary>
        internal static string AnteriorBlueEnable {
            get {
                return ResourceManager.GetString("AnteriorBlueEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior Blue Settings.
        /// </summary>
        internal static string AnteriorBlueSettings {
            get {
                return ResourceManager.GetString("AnteriorBlueSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Anterior Mode.
        /// </summary>
        internal static string AnteriorEnable {
            get {
                return ResourceManager.GetString("AnteriorEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior Settings.
        /// </summary>
        internal static string AnteriorSettings {
            get {
                return ResourceManager.GetString("AnteriorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Live Mask.
        /// </summary>
        internal static string ApplyLiveMask {
            get {
                return ResourceManager.GetString("ApplyLiveMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Live Parabola.
        /// </summary>
        internal static string ApplyLiveParabola {
            get {
                return ResourceManager.GetString("ApplyLiveParabola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Logo.
        /// </summary>
        internal static string ApplyLogo {
            get {
                return ResourceManager.GetString("ApplyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB Compensation.
        /// </summary>
        internal static string BBCompensation {
            get {
                return ResourceManager.GetString("BBCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG Compensation.
        /// </summary>
        internal static string BGCompensation {
            get {
                return ResourceManager.GetString("BGCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Command Iteration.
        /// </summary>
        internal static string BoardCommandIteration {
            get {
                return ResourceManager.GetString("BoardCommandIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BR Compensation.
        /// </summary>
        internal static string BRCompensation {
            get {
                return ResourceManager.GetString("BRCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Contrast Settings.
        /// </summary>
        internal static string BrightnessContrastSettings {
            get {
                return ResourceManager.GetString("BrightnessContrastSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Val.
        /// </summary>
        internal static string BrightnessVal {
            get {
                return ResourceManager.GetString("BrightnessVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Model.
        /// </summary>
        internal static string Camera_model {
            get {
                return ResourceManager.GetString("Camera_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Model.
        /// </summary>
        internal static string CameraModel {
            get {
                return ResourceManager.GetString("CameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Mode Settings.
        /// </summary>
        internal static string CameraModeSettings {
            get {
                return ResourceManager.GetString("CameraModeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Power Timer Interval.
        /// </summary>
        internal static string CameraPowerTimerInterval {
            get {
                return ResourceManager.GetString("CameraPowerTimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Settings.
        /// </summary>
        internal static string CameraSettings {
            get {
                return ResourceManager.GetString("CameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mode Current Boost Enable.
        /// </summary>
        internal static string Capture_Mode_Current_Boost_Enable {
            get {
                return ResourceManager.GetString("Capture_Mode_Current_Boost_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mode Current Boost Value.
        /// </summary>
        internal static string Capture_Mode_Current_Boost_Value {
            get {
                return ResourceManager.GetString("Capture_Mode_Current_Boost_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mode Current Value.
        /// </summary>
        internal static string Capture_Mode_Current_Value {
            get {
                return ResourceManager.GetString("Capture_Mode_Current_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mode Max Int Value.
        /// </summary>
        internal static string Capture_Mode_Max_Int_Value {
            get {
                return ResourceManager.GetString("Capture_Mode_Max_Int_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mode Max Percentage.
        /// </summary>
        internal static string Capture_Mode_Max_Percentage {
            get {
                return ResourceManager.GetString("Capture_Mode_Max_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Enable CC.
        /// </summary>
        internal static string CaptureEnableCC {
            get {
                return ResourceManager.GetString("CaptureEnableCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Enable WB.
        /// </summary>
        internal static string CaptureEnableWB {
            get {
                return ResourceManager.GetString("CaptureEnableWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Exposure.
        /// </summary>
        internal static string CaptureExposure {
            get {
                return ResourceManager.GetString("CaptureExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Gain.
        /// </summary>
        internal static string CaptureGain {
            get {
                return ResourceManager.GetString("CaptureGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Gain Default.
        /// </summary>
        internal static string CaptureGainDefault {
            get {
                return ResourceManager.GetString("CaptureGainDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Gain High.
        /// </summary>
        internal static string CaptureGainHigh {
            get {
                return ResourceManager.GetString("CaptureGainHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Gain Low.
        /// </summary>
        internal static string CaptureGainLow {
            get {
                return ResourceManager.GetString("CaptureGainLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Gain Medium.
        /// </summary>
        internal static string CaptureGainMedium {
            get {
                return ResourceManager.GetString("CaptureGainMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Image Height.
        /// </summary>
        internal static string CaptureImageHeight {
            get {
                return ResourceManager.GetString("CaptureImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Image ROI X.
        /// </summary>
        internal static string CaptureImageROIX {
            get {
                return ResourceManager.GetString("CaptureImageROIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Image ROI Y.
        /// </summary>
        internal static string CaptureImageROIY {
            get {
                return ResourceManager.GetString("CaptureImageROIY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Image Width.
        /// </summary>
        internal static string CaptureImageWidth {
            get {
                return ResourceManager.GetString("CaptureImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Temperature.
        /// </summary>
        internal static string CaptureTemperature {
            get {
                return ResourceManager.GetString("CaptureTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Tint.
        /// </summary>
        internal static string CaptureTint {
            get {
                return ResourceManager.GetString("CaptureTint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clahe Settings.
        /// </summary>
        internal static string ClaheSettings {
            get {
                return ResourceManager.GetString("ClaheSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip Value B.
        /// </summary>
        internal static string ClipValueB {
            get {
                return ResourceManager.GetString("ClipValueB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip Value G.
        /// </summary>
        internal static string ClipValueG {
            get {
                return ResourceManager.GetString("ClipValueG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip Value R.
        /// </summary>
        internal static string ClipValueR {
            get {
                return ResourceManager.GetString("ClipValueR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Correction Settings.
        /// </summary>
        internal static string ColorCorrectionSettings {
            get {
                return ResourceManager.GetString("ColorCorrectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast Val.
        /// </summary>
        internal static string ContrastVAl {
            get {
                return ResourceManager.GetString("ContrastVAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Voltage Settings.
        /// </summary>
        internal static string CurrentVoltageSettings {
            get {
                return ResourceManager.GetString("CurrentVoltageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Frame Detection Value.
        /// </summary>
        internal static string DarkFrameDetectionValue {
            get {
                return ResourceManager.GetString("DarkFrameDetectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Number.
        /// </summary>
        internal static string Device_number {
            get {
                return ResourceManager.GetString("Device_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Details Settings.
        /// </summary>
        internal static string DeviceDetailsSettings {
            get {
                return ResourceManager.GetString("DeviceDetailsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 14 Bit.
        /// </summary>
        internal static string Enable14Bit {
            get {
                return ResourceManager.GetString("Enable14Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Horizontal Flip.
        /// </summary>
        internal static string EnableHorizontalFlip {
            get {
                return ResourceManager.GetString("EnableHorizontalFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Raw Mode.
        /// </summary>
        internal static string EnableRawMode {
            get {
                return ResourceManager.GetString("EnableRawMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Single Frame Capture.
        /// </summary>
        internal static string EnableSingleFrameCapture {
            get {
                return ResourceManager.GetString("EnableSingleFrameCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Vertical Flip.
        /// </summary>
        internal static string EnableVerticalFlip {
            get {
                return ResourceManager.GetString("EnableVerticalFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Gain Settings.
        /// </summary>
        internal static string ExposureGainSettings {
            get {
                return ResourceManager.GetString("ExposureGainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Settings.
        /// </summary>
        internal static string FeatureSettings {
            get {
                return ResourceManager.GetString("FeatureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable FFA Mode.
        /// </summary>
        internal static string FFAEnable {
            get {
                return ResourceManager.GetString("FFAEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFA Settings.
        /// </summary>
        internal static string FFASettings {
            get {
                return ResourceManager.GetString("FFASettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Settings.
        /// </summary>
        internal static string FirmwareSettings {
            get {
                return ResourceManager.GetString("FirmwareSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Boost Value.
        /// </summary>
        internal static string FlashBoostValue {
            get {
                return ResourceManager.GetString("FlashBoostValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Offset End.
        /// </summary>
        internal static string FlashOffsetEnd {
            get {
                return ResourceManager.GetString("FlashOffsetEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Offset Start.
        /// </summary>
        internal static string FlashOffsetStart {
            get {
                return ResourceManager.GetString("FlashOffsetStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Detection Value.
        /// </summary>
        internal static string FrameDetectionValue {
            get {
                return ResourceManager.GetString("FrameDetectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain Slope.
        /// </summary>
        internal static string GainSlope {
            get {
                return ResourceManager.GetString("GainSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB Compensation.
        /// </summary>
        internal static string GBCompensation {
            get {
                return ResourceManager.GetString("GBCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GG Compensation.
        /// </summary>
        internal static string GGCompensation {
            get {
                return ResourceManager.GetString("GGCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR Compensation.
        /// </summary>
        internal static string GRCompensation {
            get {
                return ResourceManager.GetString("GRCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot Blue Peak.
        /// </summary>
        internal static string HotSpotBluePeak {
            get {
                return ResourceManager.GetString("HotSpotBluePeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot Blue Radius.
        /// </summary>
        internal static string HotSpotBlueRadius {
            get {
                return ResourceManager.GetString("HotSpotBlueRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot Correction Settings.
        /// </summary>
        internal static string HotSpotCorrectionSettings {
            get {
                return ResourceManager.GetString("HotSpotCorrectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot Green Peak.
        /// </summary>
        internal static string HotSpotGreenPeak {
            get {
                return ResourceManager.GetString("HotSpotGreenPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot Green Radius.
        /// </summary>
        internal static string HotSpotGreenRadius {
            get {
                return ResourceManager.GetString("HotSpotGreenRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotspot Radius 1.
        /// </summary>
        internal static string HotspotRadius1 {
            get {
                return ResourceManager.GetString("HotspotRadius1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotspot Radius 2.
        /// </summary>
        internal static string HotspotRadius2 {
            get {
                return ResourceManager.GetString("HotspotRadius2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot Red Peak.
        /// </summary>
        internal static string HotSpotRedPeak {
            get {
                return ResourceManager.GetString("HotSpotRedPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot Red Radius.
        /// </summary>
        internal static string HotSpotRedRadius {
            get {
                return ResourceManager.GetString("HotSpotRedRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot Settings.
        /// </summary>
        internal static string HotSpotSettings {
            get {
                return ResourceManager.GetString("HotSpotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Optical Centre X.
        /// </summary>
        internal static string ImageOpticalCentreX {
            get {
                return ResourceManager.GetString("ImageOpticalCentreX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Optical Centre Y.
        /// </summary>
        internal static string ImageOpticalCentreY {
            get {
                return ResourceManager.GetString("ImageOpticalCentreY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Shift Settings.
        /// </summary>
        internal static string ImageShiftSettings {
            get {
                return ResourceManager.GetString("ImageShiftSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Shift X.
        /// </summary>
        internal static string ImageShiftX {
            get {
                return ResourceManager.GetString("ImageShiftX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Shift Y.
        /// </summary>
        internal static string ImageShiftY {
            get {
                return ResourceManager.GetString("ImageShiftY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size Settings.
        /// </summary>
        internal static string ImageSizeSettings {
            get {
                return ResourceManager.GetString("ImageSizeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Site.
        /// </summary>
        internal static string Installation_Site {
            get {
                return ResourceManager.GetString("Installation_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation City.
        /// </summary>
        internal static string InstallationCity {
            get {
                return ResourceManager.GetString("InstallationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Country.
        /// </summary>
        internal static string InstallationCountry {
            get {
                return ResourceManager.GetString("InstallationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Details Settings.
        /// </summary>
        internal static string InstallationDetailsSettings {
            get {
                return ResourceManager.GetString("InstallationDetailsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Pincode.
        /// </summary>
        internal static string InstallationPinCode {
            get {
                return ResourceManager.GetString("InstallationPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation State.
        /// </summary>
        internal static string InstallationState {
            get {
                return ResourceManager.GetString("InstallationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Brightness.
        /// </summary>
        internal static string IsApplyBrightness {
            get {
                return ResourceManager.GetString("IsApplyBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Apply Clahe Settings.
        /// </summary>
        internal static string IsApplyClaheSettings {
            get {
                return ResourceManager.GetString("IsApplyClaheSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply ColorCorrection.
        /// </summary>
        internal static string IsApplyColorCorrection {
            get {
                return ResourceManager.GetString("IsApplyColorCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Contrast.
        /// </summary>
        internal static string IsApplyContrast {
            get {
                return ResourceManager.GetString("IsApplyContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Hotspot Correction.
        /// </summary>
        internal static string IsApplyHotspotCorrection {
            get {
                return ResourceManager.GetString("IsApplyHotspotCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Image Shift.
        /// </summary>
        internal static string IsApplyImageShift {
            get {
                return ResourceManager.GetString("IsApplyImageShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Lut.
        /// </summary>
        internal static string IsApplyLutSettings {
            get {
                return ResourceManager.GetString("IsApplyLutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Capture Mask.
        /// </summary>
        internal static string IsApplyMask {
            get {
                return ResourceManager.GetString("IsApplyMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Ply.
        /// </summary>
        internal static string IsApplyPly {
            get {
                return ResourceManager.GetString("IsApplyPly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Unsharp.
        /// </summary>
        internal static string IsApplyUnsharpSettings {
            get {
                return ResourceManager.GetString("IsApplyUnsharpSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Vignatting.
        /// </summary>
        internal static string IsApplyVignatting {
            get {
                return ResourceManager.GetString("IsApplyVignatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable L R Sensor.
        /// </summary>
        internal static string IsEnableLeftRightSensor {
            get {
                return ResourceManager.GetString("IsEnableLeftRightSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Flash Boost.
        /// </summary>
        internal static string IsFlashBoost {
            get {
                return ResourceManager.GetString("IsFlashBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Motor Compensation.
        /// </summary>
        internal static string IsMotorCompensation {
            get {
                return ResourceManager.GetString("IsMotorCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Polarity Forward.
        /// </summary>
        internal static string IsMotorPolarityForward {
            get {
                return ResourceManager.GetString("IsMotorPolarityForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is USB Communication.
        /// </summary>
        internal static string IsUSBCommunication {
            get {
                return ResourceManager.GetString("IsUSBCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mode Current Boost Enable.
        /// </summary>
        internal static string Live_Mode_Current_Boost_Enable {
            get {
                return ResourceManager.GetString("Live_Mode_Current_Boost_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mode Current Boost Value.
        /// </summary>
        internal static string Live_Mode_Current_Boost_Value {
            get {
                return ResourceManager.GetString("Live_Mode_Current_Boost_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mode Current Value.
        /// </summary>
        internal static string Live_Mode_Current_Value {
            get {
                return ResourceManager.GetString("Live_Mode_Current_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mode Max Int Value.
        /// </summary>
        internal static string Live_Mode_Max_Int_Value {
            get {
                return ResourceManager.GetString("Live_Mode_Max_Int_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mode Max Percentage.
        /// </summary>
        internal static string Live_Mode_Max_Percentage {
            get {
                return ResourceManager.GetString("Live_Mode_Max_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mode Voltage Value.
        /// </summary>
        internal static string Live_Mode_Voltage_Value {
            get {
                return ResourceManager.GetString("Live_Mode_Voltage_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Enable CC.
        /// </summary>
        internal static string LiveEnableCC {
            get {
                return ResourceManager.GetString("LiveEnableCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Enable WB.
        /// </summary>
        internal static string LiveEnableWB {
            get {
                return ResourceManager.GetString("LiveEnableWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Exposure.
        /// </summary>
        internal static string LiveExposure {
            get {
                return ResourceManager.GetString("LiveExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Gain.
        /// </summary>
        internal static string LiveGain {
            get {
                return ResourceManager.GetString("LiveGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Gain Default.
        /// </summary>
        internal static string LiveGainDefault {
            get {
                return ResourceManager.GetString("LiveGainDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Gain High.
        /// </summary>
        internal static string LiveGainHigh {
            get {
                return ResourceManager.GetString("LiveGainHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Gain Low.
        /// </summary>
        internal static string LiveGainLow {
            get {
                return ResourceManager.GetString("LiveGainLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Gain Medium.
        /// </summary>
        internal static string LiveGainMedium {
            get {
                return ResourceManager.GetString("LiveGainMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Image Height.
        /// </summary>
        internal static string LiveImageHeight {
            get {
                return ResourceManager.GetString("LiveImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Image ROI X.
        /// </summary>
        internal static string LiveImageROIX {
            get {
                return ResourceManager.GetString("LiveImageROIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Image ROI Y.
        /// </summary>
        internal static string LiveImageROIY {
            get {
                return ResourceManager.GetString("LiveImageROIY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Image Width.
        /// </summary>
        internal static string LiveImageWidth {
            get {
                return ResourceManager.GetString("LiveImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mask Height.
        /// </summary>
        internal static string LiveMaskHeight {
            get {
                return ResourceManager.GetString("LiveMaskHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mask Width.
        /// </summary>
        internal static string LiveMaskWidth {
            get {
                return ResourceManager.GetString("LiveMaskWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Temperature.
        /// </summary>
        internal static string LiveTemperature {
            get {
                return ResourceManager.GetString("LiveTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Tint.
        /// </summary>
        internal static string LiveTint {
            get {
                return ResourceManager.GetString("LiveTint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lut Interval 1.
        /// </summary>
        internal static string LutInterval1 {
            get {
                return ResourceManager.GetString("LutInterval1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lut Interval 2.
        /// </summary>
        internal static string LutInterval2 {
            get {
                return ResourceManager.GetString("LutInterval2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lut Offset.
        /// </summary>
        internal static string LutOffset {
            get {
                return ResourceManager.GetString("LutOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lut Settings.
        /// </summary>
        internal static string LutSettings {
            get {
                return ResourceManager.GetString("LutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lut Sine Factor.
        /// </summary>
        internal static string LutSineFactor {
            get {
                return ResourceManager.GetString("LutSineFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mask Height.
        /// </summary>
        internal static string MaskHeight {
            get {
                return ResourceManager.GetString("MaskHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Settings.
        /// </summary>
        internal static string MaskSettings {
            get {
                return ResourceManager.GetString("MaskSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mask Width.
        /// </summary>
        internal static string MaskWidth {
            get {
                return ResourceManager.GetString("MaskWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median Filter Size.
        /// </summary>
        internal static string MedFilter {
            get {
                return ResourceManager.GetString("MedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor End Point Backward.
        /// </summary>
        internal static string Motor_EndPoint_Backward {
            get {
                return ResourceManager.GetString("Motor_EndPoint_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor End Point Forward.
        /// </summary>
        internal static string Motor_EndPoint_Forward {
            get {
                return ResourceManager.GetString("Motor_EndPoint_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Reset Position.
        /// </summary>
        internal static string Motor_Reset_Position {
            get {
                return ResourceManager.GetString("Motor_Reset_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Steps Range.
        /// </summary>
        internal static string Motor_Steps_Range {
            get {
                return ResourceManager.GetString("Motor_Steps_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Zero D Position.
        /// </summary>
        internal static string Motor_ZeroD_Position {
            get {
                return ResourceManager.GetString("Motor_ZeroD_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live to Capture Motor Steps.
        /// </summary>
        internal static string MotorCompensationStepsIR2Flash {
            get {
                return ResourceManager.GetString("MotorCompensationStepsIR2Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Ply Steps.
        /// </summary>
        internal static string MotorPlySteps {
            get {
                return ResourceManager.GetString("MotorPlySteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Settings.
        /// </summary>
        internal static string MotorSettings {
            get {
                return ResourceManager.GetString("MotorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optics Version.
        /// </summary>
        internal static string Optics_Version {
            get {
                return ResourceManager.GetString("Optics_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Posterior Mode.
        /// </summary>
        internal static string PosteriorEnable {
            get {
                return ResourceManager.GetString("PosteriorEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posterior Settings.
        /// </summary>
        internal static string PosteriorSettings {
            get {
                return ResourceManager.GetString("PosteriorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Processing Settings.
        /// </summary>
        internal static string PostProcessingSettings {
            get {
                return ResourceManager.GetString("PostProcessingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Batch.
        /// </summary>
        internal static string Production_batch {
            get {
                return ResourceManager.GetString("Production_batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RB Compensation.
        /// </summary>
        internal static string RBCompensation {
            get {
                return ResourceManager.GetString("RBCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG Compensation.
        /// </summary>
        internal static string RGCompensation {
            get {
                return ResourceManager.GetString("RGCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR Compensation.
        /// </summary>
        internal static string RRCompensation {
            get {
                return ResourceManager.GetString("RRCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Frames Count.
        /// </summary>
        internal static string SaveFramesCount {
            get {
                return ResourceManager.GetString("SaveFramesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Blue Percentage.
        /// </summary>
        internal static string ShadowBluePercentage {
            get {
                return ResourceManager.GetString("ShadowBluePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Correction Settings.
        /// </summary>
        internal static string ShadowCorrectionSettings {
            get {
                return ResourceManager.GetString("ShadowCorrectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Green Percentage.
        /// </summary>
        internal static string ShadowGreenPercentage {
            get {
                return ResourceManager.GetString("ShadowGreenPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Rad Spot 1.
        /// </summary>
        internal static string ShadowRadSpot1 {
            get {
                return ResourceManager.GetString("ShadowRadSpot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Rad Spot 2.
        /// </summary>
        internal static string ShadowRadSpot2 {
            get {
                return ResourceManager.GetString("ShadowRadSpot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Red Percentage.
        /// </summary>
        internal static string ShadowRedPercentage {
            get {
                return ResourceManager.GetString("ShadowRedPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Tint Settings.
        /// </summary>
        internal static string TemperatureTintSettings {
            get {
                return ResourceManager.GetString("TemperatureTintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSharp Amount.
        /// </summary>
        internal static string UnSharpAmount {
            get {
                return ResourceManager.GetString("UnSharpAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharp Mask Settings.
        /// </summary>
        internal static string UnsharpMaskSettings {
            get {
                return ResourceManager.GetString("UnsharpMaskSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharp Radius.
        /// </summary>
        internal static string UnSharpRadius {
            get {
                return ResourceManager.GetString("UnSharpRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharp Threshold.
        /// </summary>
        internal static string UnSharpThreshold {
            get {
                return ResourceManager.GetString("UnSharpThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vignatting% Factor Live.
        /// </summary>
        internal static string VignattingPercentageFactorLive {
            get {
                return ResourceManager.GetString("VignattingPercentageFactorLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vignatting % Factor PP.
        /// </summary>
        internal static string VignattingPercentageFactorPostProcessing {
            get {
                return ResourceManager.GetString("VignattingPercentageFactorPostProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vignatting Radius Live.
        /// </summary>
        internal static string VignattingRadiusLive {
            get {
                return ResourceManager.GetString("VignattingRadiusLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vignatting Radius PP.
        /// </summary>
        internal static string VignattingRadiusPostProcessing {
            get {
                return ResourceManager.GetString("VignattingRadiusPostProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vignatting Settings.
        /// </summary>
        internal static string VignattingSettings {
            get {
                return ResourceManager.GetString("VignattingSettings", resourceCulture);
            }
        }
    }
}
